#! /bin/sh

# Set wallpaper
feh --bg-scale /home/birdt/.bg.png

# Start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# bspc config
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 8

bspc config normal_border_color "#BD7979"
bspc config focused_border_color "#F05D5E"

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# Launch picom
pgrep -x picom > /dev/null || picom -b

# Network manager applet
pgrep -x nm-applet > /dev/null || nm-applet &

# Power Manager
pgrep -x xfce4-power-manager > /dev/null || xfce4-power-manager &

# Pipewire
pgrep -x pipewire > /dev/null || pipewire &

# Start xfce4-panel and force the window manager above it
pgrep -x xfce4-panel > /dev/null || xfce4-panel --disable-wm-check &
sleep 45
xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" $(xdo id -n xfce4-panel)
